network: "networks/prenetwork2_sn20.nc"

tatl_factor:
  start: 1
  stop: 2
  step: 0.1


snapshots: 20

flex_cost:
  start: 100
  stop: 18100
  step: 6000


solver:
  name: gurobi
  threads: 4
  method: 2
  crossover: 0
  BarConvTol: 1.e-3
  FeasibilityTol: 1.e-4
  AggFill: 0
  PreDual: 0
  GURO_PAR_BARDENSETHRESH: 200
  BarHomogeneous: 1
