
network: "networks/elec_s_50_ec_lv1.0_Co2L0.1-1H.nc"  #3_bus.nc

load_shedding: true

tatl_factor:
  start: 1
  stop: 2
  step: 0.1

solver:
  name: gurobi
  threads: 4
  method: 2
  crossover: 0
  BarConvTol: 1.e-3
  FeasibilityTol: 1.e-4
  AggFill: 0
  PreDual: 0
  GURO_PAR_BARDENSETHRESH: 200
  BarHomogeneous: 1

sclopf:
  pyomo: False
  solver_name: gurobi
  formulation: kirchhoff
