import numpy as np


configfile: "config.yaml"


rule preprocess_network:
    input: config["network"]
    output: "networks/prenetwork_Co2L{Co2factor}_sn{n_snapshots}.nc"
    resources: mem = 5000
    script: "scripts/preprocess_network.py"


rule solve_full_contingency:
    input: "networks/prenetwork_Co2L{Co2factor}_sn{n_snapshots}.nc"
    output: "results/postnetwork_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.nc"
    threads: 4
    resources: mem= 5000#50000
    script: "scripts/full_contingency_tatl_test.py"


rule solve_netzbooster:
    input: "results/postnetwork_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.nc"
    output:
        P   = "results/P_netzbooster_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv",
        pos = "results/p_pos_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv",
        neg = "results/p_neg_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv"
    threads: 4
    log:
        mem    = "log/seq_memory_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.log",
        gurobi = "log/seq_gurobi_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.log"
    resources: mem = 15000 #(sn=150)
    script: "scripts/netzbooster_seq.py"


rule all:
    input:
        booster = expand("results/P_netzbooster_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv",
                         Co2factor   = config["co2_factor"],
                         n_snapshots = config["n_snapshots"],
                         tatlfactor  = config["tatl_factor"]),
        booster_pos = expand("results/p_pos_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv",
		                     Co2factor   = config["co2_factor"],
                             n_snapshots = config["n_snapshots"],
                             tatlfactor  = config["tatl_factor"]),
        booster_neg = expand("results/p_neg_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.csv",
		                     Co2factor   = config["co2_factor"],
                             n_snapshots = config["n_snapshots"],
                             tatlfactor  = config["tatl_factor"]),
        full = expand("results/postnetwork_Co2L{Co2factor}_sn{n_snapshots}_tatl{tatlfactor}.nc",
		              Co2factor   = config["co2_factor"],
                      n_snapshots = config["n_snapshots"],
                      tatlfactor  = config["tatl_factor"])
