network: "networks/prenetwork1_sn20.nc"


snapshots: 20 


tatl_factor:
  start: 1.8
  stop: 2.0
  step: 0.2
  
  

# flex_cost: 18100 

flex_cost:
  start: 0 
  stop: 23000
  step: 23000 #6000


solver:
  name: gurobi
  threads: 4
  method: 2
  crossover: 0
  BarConvTol: 1.e-3
  FeasibilityTol: 1.e-4
  AggFill: 0
  PreDual: 0
  GURO_PAR_BARDENSETHRESH: 200
  BarHomogeneous: 1
