import numpy as np

configfile: "config.yaml"
configfile: "../netzbooster-model/config.yaml"


rule netzbooster:
    input:
        network  = "../netzbooster-model/networks/prenetwork_Co2L{Co2factor}_sn{n_snapshots}.nc",
        variable = "data/variables.csv"
    output:
        network = "results/postnetwork_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                  "_cost{flex_cost}_tatl{tatlfactor}.nc",
        P       = "results/P_netzbooster_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                  "_cost{flex_cost}_tatl{tatlfactor}.csv",
        pos     = "results/p_pos_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                   "_cost{flex_cost}_tatl{tatlfactor}.csv",
        neg     = "results/p_neg_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                  "_cost{flex_cost}_tatl{tatlfactor}.csv"
    threads: 4
    resources: mem = 50000
    script: "scripts/netzbooster_sim_tatl.py"


rule all:
    input:
        booster_P       = expand("results/P_netzbooster_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                                 "_cost{flex_cost}_tatl{tatlfactor}.csv",
	                             Co2factor   = config["co2_factor"],
                                 n_snapshots = config["n_snapshots"],
                                 flex_cost   = config["flex_cost"],
                                 tatlfactor  = config["tatl_factor"]),
        booster_pos     = expand("results/p_pos_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                                 "_cost{flex_cost}_tatl{tatlfactor}.csv",
                                 Co2factor   = config["co2_factor"],
                                 n_snapshots = config["n_snapshots"],
                                 flex_cost   = config["flex_cost"],
                                 tatlfactor  = config["tatl_factor"]),
        booster_neg     = expand("results/p_neg_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                                 "_cost{flex_cost}_tatl{tatlfactor}.csv",
                                 Co2factor   = config["co2_factor"],
                                 n_snapshots = config["n_snapshots"], 
                                 flex_cost   = config["flex_cost"], 
                                 tatlfactor  = config["tatl_factor"]),
        booster_network = expand("results/postnetwork_sclopf_Co2L{Co2factor}_sn{n_snapshots}"+
                                 "_cost{flex_cost}_tatl{tatlfactor}.nc",
                                 Co2factor   = config["co2_factor"], 
                                 n_snapshots = config["n_snapshots"], 
                                 flex_cost   = config["flex_cost"], 
                                 tatlfactor  = config["tatl_factor"])
